export const steps = [
  { name: "مشخصات عمومی", id: 1 },
  { name: "نوع سازمان", id: 2 },
  { name: "قابلیت های خاص", id: 3 },
  { name: "فاکتورهای کلیدی", id: 4 },
];

export const general = [
  { name: "مخزن / متامدل", id: "repo_meta", checked: false },
  { name: "مدل سازی", id: "model", checked: false },
  { name: "تجزیه تحلیل و کمک به تصمیم گیری", id: "decision", checked: false },
  { name: "قابلیت ارائه", id: "present", checked: false },
  { name: "قابلیت های مدیریتی (ادمین)", id: "admin", checked: false },
  { name: "قابلیت پیکربندی", id: "config", checked: false },
  { name: "برخورداری از چارچوب های استاندارد", id: "std", checked: false },
  { name: "قابلیت استفاده", id: "use", checked: false },
];

export const organization = [
  { name: "بانکی", id: "bank" },
  { name: "دولتی", id: "gov" },
  { name: "فناوری اطلاعات", id: "it" },
  { name: "سلامت", id: "health" },
  { name: "بیمه", id: "insurance" },
  { name: "مالی (غیر بانکی)", id: "financial" },
  { name: "ساخت و ساز", id: "manu" },
  { name: "آموزشی", id: "edu" },
  { name: "خرده فروشی", id: "retail" },
  { name: "فروش کالا", id: "commodities" },
  { name: "نیرو و انرژی", id: "energy" },
  { name: "سایر", id: "other" },
];

export const features = [
  {
    name: "قابلیت های وارد کردن / استخراج داده",
    id: "import_export",
    checked: false,
  },
  { name: "انعطاف پذیری برنامه", id: "flexibility", checked: false },
  { name: "پیکربندی مدل ها", id: "metamodel_configuration", checked: false },
  { name: "نصب و راه اندازی سریع", id: "quick_setup", checked: false },
  { name: "قابلیت های تجزیه و تحلیل وضعیت", id: "analyze", checked: false },
  { name: "مدیریت ریسک", id: "risk", checked: false },
  {
    name: "قابلیت های out-of-the-boxفریم ورک های متعدد",
    id: "standard_framework",
    checked: false,
  },
  { name: "قابلیت های out-of-the-box", id: "out_of_box", checked: false },
  { name: "گزارش دهی", id: "report", checked: false },
  { name: "پورتال های ارتباطی", id: "portal", checked: false },
  { name: "ادغام با سایر برنامه ها", id: "integration", checked: false },
  { name: "مدل سازی پیشرفته", id: "modeling_features", checked: false },
  { name: "جستجو در مخازن و متامدل ها", id: "search", checked: false },
  { name: "مدیریت پورتفولیو", id: "portfolio", checked: false },
  { name: "رابط کاربری", id: "interface", checked: false },
  { name: "ویژگی های تجسمی", id: "visualization", checked: false },
  { name: "کمک به تصمیم گیری", id: "decision_making", checked: false },
  { name: "قابلیت همکاری تیمی", id: "collab", checked: false },
  { name: "تیم پشتیبانی قوی", id: "support", checked: false },
  { name: "مبتنی بر ابر", id: "cloud", checked: false },
  { name: "هزینه کم", id: "cost", checked: false },
  { name: "متدولوژی اجایل", id: "agile", checked: false },
  { name: "سفارشی سازی برنامه", id: "customize", checked: false },
  { name: "نظرسنجی", id: "survey", checked: false },
  { name: "شبیه سازی", id: "simulate", checked: false },
  { name: "ویرایشگر کد درون برنامه ای", id: "IDE", checked: false },
  { name: "تبدیل مدل به کد", id: "model_to_code", checked: false },
  { name: "آپدیت های منظم", id: "regular_update", checked: false },
  { name: "UML", id: "UML", checked: false },
  { name: "اتوماسیون", id: "automation", checked: false },
  { name: "پشتیبانی از API", id: "api", checked: false },
  { name: "قابلیت های به اشتراک گذاری", id: "share", checked: false },
  { name: "قابلیت های ارائه به افراد", id: "present", checked: false },
  { name: "استفاده آسان", id: "easy_use", checked: false },
];

export const factors = [
  { name: "عملکرد محصول", id: "function", checked: false },
  { name: "وسعت خدمات", id: "breadth", checked: false },
  { name: "هزینه کلی", id: "total_cost", checked: false },
  { name: "جامعه کاربری قوی", id: "powerfull_users", checked: false },
  { name: "مشتری مداری قوی", id: "customer", checked: false },
  { name: "روابط از قبل موجود", id: "relation", checked: false },
  { name: "نقشه راه محصول و چشم انداز آینده", id: "road", checked: false },
  { name: "خدمات تخصصی قوی", id: "expert", checked: false },
  { name: "مشارکت و مشاوره قوی", id: "partnership", checked: false },
  { name: "تمرکز بر مشتری", id: "focus", checked: false },
  { name: "دوام مالی/سازمانی", id: "sustain", checked: false },
];
